name: nobes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  animated_icon_button: ^1.0.2
  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  mysql_client: ^0.0.27
  d_chart: ^2.2.11
  dio: ^5.0.3
  tutorial_coach_mark: ^1.2.9
  dropdown_button2: ^2.1.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^1.7.1
  flutter_staggered_animations: ^1.1.1
  get: 4.6.5
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_picker: ^0.8.7+2
  intl: ^0.18.0
  pull_to_refresh: ^2.0.0
  search_page: ^2.3.0
  translator: ^0.1.7
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: digital
      fonts:
        - asset: assets/fonts/digital-7.ttf
        - asset: assets/fonts/digital-7 (italic).ttf
          style: italic

#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
